# Generated by Django 3.0 on 2022-03-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220301_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='comments',
        ),
    ]
